### ISSUE TITLE
Error: Could not find valid cookie for authentication.

### ISSUE THREAD

**Issue by yorsant** [passageidentity/supabase-passage-example#5]
I'm following the [instructions](https://docs.passage.id/helpful-guides/supabase-integration-guide) for a next js app but using the new app router instead of the pages router.
Once I call `passage.authenticateRequest(req)` I get **Error: Could not find valid cookie for authentication.**

These are the cookies in my browser after successful authentication. 
![Screenshot 2023-06-10 at 11 39 09 PM](https://github.com/passageidentity/supabase-passage-example/assets/12414043/5064582c-b32a-4761-ac59-1d6c6b27f3f3)

Is this a bug on `Passage`?

**Comment by himichaelroberts** [comment]
Hi @yorsant, we are currently in the process of having a Next.js App Router example that can be found [here](https://github.com/passageidentity/example-nextjs/pull/6).

If you want to validate the cookie server side for an API route, you can use the following.

```
import { cookies } from "next/headers";
import Passage from "@passageidentity/passage-node";

const passage = new Passage({
  appID: process.env.NEXT_PUBLIC_PASSAGE_APP_ID as string,
});

export async function GET() {
  const cookieStore = cookies();

  const authToken = cookieStore.get("psg_auth_token")?.value;

  if (!authToken) return new Response("Unauthorized", { status: 401 });

  const user = await passage.validAuthToken(authToken);

  if (user) return new Response("Authorized!", { status: 200 });

  return new Response("Unauthorized", { status: 401 });
}
```
